empportal/attendance/urls.py
from django.urls import path
from django.http import HttpResponse
def fun(request):
    return HttpResponse("hello")

app_name = "attendance"
urlpatterns = [
    path("attendance_create_emp/", fun, name="create_emp"),
    
]

empportal/emp/urls.py
from django.http.response import HttpResponse
from emp.views import get_employees, create_emp, update_emp,\
    delete_emp
from django.urls import path
from django.http import HttpResponse
app_name = "emp"
def fun(request):
    return HttpResponse("from urls")
urlpatterns = [
    path("", get_employees),
    #path("createEmp/", fun, name="create1_emp"),#emp/createEmp/
    path("createEmp/", create_emp, name="create_emp"),
    path("updateEmp/<int:emp_id>/", update_emp, name="updateEmp"),
    path("deleteEmp/<int:emp_id>/", delete_emp, name="deleteEmp"),
    #http://localhost:8000/emp/updateEmp/7/
    # update_emp(request_obj, emp_id=7)
    
]

empportal/empportal/urls.py
from django.contrib import admin
from django.urls import path, include
from emp.methods import get_users, get_cpu_cores
from emp.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", get_users),# get_users(request_object)
    path("numberOfCores/", get_cpu_cores),
    path('', home),
    path("emp/", include("emp.urls")),
    path("attendance/", include('attendance.urls'))
]

empportal/emp/models.py
from django.db import models

# Create your models here.
class Emp(models.Model):
    emp_type_choices =[('ADMIN','ADMIN'),('HR','HR'),('EMPLOYEE','EMPLOYEE')]
    empid = models.CharField(max_length=15, unique=True)#varchar
    name = models.CharField(max_length=250)
    address=models.CharField(max_length=600, null=True, blank=True)
    salary_perday = models.PositiveIntegerField(blank=True)
    emp_type = models.CharField(choices=emp_type_choices, max_length=10) 
    email = models.EmailField(max_length=250, blank=True)
    phone = models.CharField(max_length=15, null=True)

    def __str__(self):
        return f"{self.name} - {self.salary_perday}"

empportal/attendance/views.py
from django.shortcuts import render

# Create your views here.

empportal/emp/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from emp.models import Emp
#from django.http import HttpResponse

def delete_emp(request, emp_id):
    emp_ins = Emp.objects.get(id=emp_id)
    if request.method == "POST":
        if 'submit' in request.POST:
            emp_ins.delete()
        return redirect("/emp/")
    return render(request, "emp/confirm.html", {"emp":emp_ins })

def update_emp(request, emp_id):
    emp_ins = Emp.objects.get(id=emp_id)
    if request.method=="POST":
        new_data = request.POST
        emp_ins.name =  new_data.get("name")
        emp_ins.empid = new_data.get("empid")
        emp_ins.salary_perday = new_data.get("salary_perday")
        emp_ins.email = new_data.get("email")
        emp_ins.phone = new_data.get("phone")
        emp_ins.address = new_data.get("address")
        emp_ins.emp_type = new_data.get("emp_type")
        emp_ins.save()
        return redirect('/emp/')
        # emps = Emp.objects.all() 
        # return render(request, "emp/emps.html", {"emps": emps})

    return render(request, 'emp/create.html', {"data":emp_ins})
    import pdb;pdb.set_trace()



def create_emp(request):
    #return HttpResponse("hello")
    print("*"*20)
    print(request.method)
    if request.method == "POST":
        act_data = request.POST
        data = {"name": act_data.get("name"),
        "empid": act_data.get("empid"),
        "salary_perday": act_data.get("salary_perday"),
        "email": act_data.get("email"),
        "phone": act_data.get("phone"),
        "address": act_data.get("address"),
        "emp_type": act_data.get("emp_type"),
        }
        emp_inst = Emp(**data)
        emp_inst.save()
        return redirect('/emp/')
        # emps = Emp.objects.all() 
        # return render(request, "emp/emps.html", {"emps": emps})

    type_choices = Emp.emp_type_choices
    return render(request, "emp/create.html", {"emp_types": type_choices})

def get_employees(request):
    emps = Emp.objects.all()
    #emps is the list of Emp class(django model) instances. 
    #return HttpResponse(emps)
    # Above return statement will throw an error. Django server not able to understand the 
    # django model instances.
    #serialization. we need to convert list of django model instances to list of dictionaires.
    #data = [{"name":emp.name,"salary":emp.salary_perday} for emp in emps]

    #return HttpResponse(data)
    return render(request, "emp/emps.html", {"emps": emps})

# Create your views here.
def home(request):
    # resp = """
    # <html>
    # <body>
    # <h1>HOME</h1>
    # </body>
    # </html>
    # """
    #return HttpResponse("HOME")
    #1. we need to write this html content in html file
    #2. read the html content from html file 
    #3. prepare HttpREsponse object
    #2,3 will be done by render function 
    # home.html
    #return HttpResponse(resp)
    employees = [{"name":"Hameer"},{"name":"Anil"},{"name":"Vamshi"}]
    data = {"title":"Empportal", "header":"PORTAL"}
    context = {"data": data, "employees": employees}
    return render(request, "home.html", context)
    # render has to serach for home.html

empportal/emp/templates/emp/confirm.html
<html>
    <body>
        <h1>DELETE EMP</h1>
        <ul>
            <li>NAME: {{ emp.name}}</li>
            <li>empid: {{ emp.id}}</li>
        </ul>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="submit" name="submit">
            <input type="submit" value="cancel" name="cancel">
        </form>
    </body>
</html>

empportal/emp/templates/emp/create.html
<html>
    <body>
        <form method="POST">
            {% csrf_token %}
            name: <input type="text" name="name" value="{{data.name}}"><br>
            empid: <input type="text" name="empid" value="{{data.empid}}"><br>
            address: <input type="text" name="address" value="{{data.address}}"><br>
            salary_perday: <input type="text" name="salary_perday" value="{{data.salary_perday}}"><br>
            emp_type: <select name="emp_type">
                <option value="ADMIN">ADMIN</option>
                <option value="HR">HR</option>
                <option value="EMPLOYEE">EMPLOYEE</option>
            </select><br>
            email: <input type="text" name="email" value="{{data.email}}"><br>
            phone: <input type="text" name="phone" value="{{data.phone}}"><br>
            <input type="submit" value="submit">
        </form>
    </body>
</html>

empportal/emp/templates/emp/emps.html
<html>
    <head></head>
    <body>
        <h1> EMPLOYEES </h1>
        <a href="{% url 'emp:create_emp' %}">CREATE EMPLOYEE</a>
        <br>
        <h1></h1>
        <table border="2">
            <tr><th>Name</th><th>SALARY PERDAY</th>
            <th>OPERATIONS</th>
            </tr>
            {% for emp in emps%}
            <tr>
                <td>{{ emp.name}}</td><td>{{ emp.salary_perday }}</td>
                <td><a href="{% url 'emp:updateEmp' emp.id %}">UPDATE</a> -- 
                    <a href="{% url 'emp:deleteEmp' emp.id %}">DELETE</a></td>
            </tr>
            {% endfor %}

        </table>
    </body>
</html>

empportal/emp/templates/home.html
<html>
    <body>
    <h1>{{ data.header}}</h1>
    <p>{{ data.title }}</p>
    <!-- <p>{{ employees }}</p>
    <p>{{ salaries }}</p> -->
    <!-- <ol>
        <li>HAMEER</li>
        <li>ANIL</li>
        <li>VAMSHI</li>
    </ol> -->
    <ol>
        {% for emp in employees %}
            <li>{{ emp.name|upper }}</li>
        {% endfor %}
    </ol>
    </body>
    </html>