sales/api/urls.py
from django.urls import path, include
from api.views import CategoryAPIView, TokenView, ProductModelViewSet
urlpatterns = [
    path("category/<int:pk>/", CategoryAPIView.as_view()),
    path("category/", CategoryAPIView.as_view()),# GET
    path("token/", TokenView.as_view()),
    path("product/<int:pk>/", ProductModelViewSet.as_view({
        "get":"retrieve",
        "put":"update",
        "delete":"destroy",
        #"patch":"patch_update",
    })),#get,put,delete,patch
    path("product/", ProductModelViewSet.as_view({
        "post":"create",
        "get":"list"
    }))#get,post
    
]

sales/sales/urls.py
from django.contrib import admin
from django.contrib.messages.api import success
from django.urls import path, include
from product.models import Category
from product.views import view_hide_category, view_products, view_sales,\
    view_sales_create, view_customers, view_create_customer, view_update_customer,\
    view_delete_customer, view_product_create

from product import user_auth
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView, CreateView, UpdateView,\
    DeleteView, ListView
from product.forms import CategoryForm

urlpatterns = [
    path("api/", include("api.urls")),
    path('admin/', admin.site.urls),
    #path('categories/', view_categories),# view_categories(request_obj)
    path('categories/', ListView.as_view(
        model = Category,
        template_name="categories.html",
        paginate_by=10
    )),# view_categories(request_obj)
    #path('category/create/', view_create_category),
    path('category/create/', CreateView.as_view(
        model = Category,
        fields = ["name","discount"],
        #exclude = ["hide", "created_at"],
        #form_class = CategoryForm,
        success_url = "/categories/",
        template_name="create_category.html"
        # default template: category_form.html
    )),
    #path('category/update/<int:cat_id>/', view_update_category),
    path('category/update/<int:pk>/', UpdateView.as_view(
        model = Category,
        fields = ["name","discount"],
        #exclude = ["hide", "created_at"],
        #form_class = CategoryForm,
        success_url = "/categories/",
        template_name="create_category.html"
        # default template: category_form.html 
    )),
    #view_update_category(request_obj, cat_id=5)
    #path('category/delete/<int:cat_id>/', view_delete_category),
    path('category/delete/<int:pk>/', DeleteView.as_view(
        model=Category,
        success_url = "/categories/",
        template_name="confirm.html",
    )),
    #view_delete_category(request_obj, cat_id=1)
    path('category/hide/<int:cat_id>/', view_hide_category),
    path('customers/', view_customers),# view_categories(request_obj)
    path('customer/create/', view_create_customer),# RequestCheck(view_create_customer).__call__(request)
    path('customer/update/<int:cust_id>/', view_update_customer),
    #view_update_customer(request_obj, cat_id=5)
    path('customer/delete/<int:cust_id>/', view_delete_customer),
    #view_delete_customer(request_obj, cat_id=1)
    # path('customer/hide/<int:cust_id>/', view_hide_customer),
    #path("", view_index),
    path("", TemplateView.as_view(
        template_name="base.html",
        )),
    path("products/", view_products),
    path("sales/", view_sales),
    path("sales/create/", view_sales_create),
    path("signin/",user_auth.view_signin),
    path("signup/",user_auth.view_signup),
    path("signout/", user_auth.view_signout),
    path("product/create/", view_product_create)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/product/models.py
from django.db import models
from product.validations import validate_name
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

class BaseAbstarctModel(models.Model):# Abstract model
    name=models.CharField(max_length=250, validators=[validate_name])
    created_at = models.DateTimeField(default=datetime.now())
    class Meta:
        abstract=True

# class MyUser(User): # inherited model
#     #it will create myuser table in db after migrate.
#     # we have inherited this model from user, i.e it will create a one to one relationship
#     # with User model
#     phone = models.CharField(max_length=250, default="", null=True)
#     adhar = models.CharField(max_length=250, default="", null=True)
#     pan = models.CharField(max_length=250, default="", null=True)
#     passport = models.CharField(max_length=250, default="", null=True)

class MyUser(AbstractUser):
    phone = models.CharField(max_length=250, default="", null=True)
    adhar = models.CharField(max_length=250, default="", null=True)
    pan = models.CharField(max_length=250, default="", null=True)
    passport = models.CharField(max_length=250, default="", null=True)

# Create your models here.
class Category(BaseAbstarctModel):
    #name=models.CharField(max_length=250, validators=[validate_name])
    hide = models.BooleanField(default=False)
    discount = models.PositiveIntegerField(default=0)

    def __str__(self):
        return  "%s-%s" %(self.name, self.discount)
    
    # def data(self):
    #     return {"name":self.name,"discount":self.discount}

class Product(BaseAbstarctModel):
    #name = models.CharField(max_length=250)
    cost = models.PositiveIntegerField(default=0)
    deliver_charges = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    #category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.FileField(default="")
    #many to one
    #category = models.CharField(max_length=250)
    # in this column we can add only category table id column values only

    def __str__(self):
        return self.name
    

class Customer(BaseAbstarctModel):
    pass
    #name = models.CharField(max_length=250)
    # address = models.Textfield(max_length=650)
    # phone = models.CharField(max_length=11)
    # email = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Sales(models.Model):
    description = models.CharField(max_length=250)
    products = models.ManyToManyField(Product, through='SalesProducts')
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)

class SalesProducts(models.Model):
    sales = models.ForeignKey(Sales, on_delete=models.PROTECT)
    #product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    cost = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=1)



    

sales/product/forms.py
from django.db import models
from django.db.models import fields
from django.forms import ModelForm, formset_factory
from product.models import Category, Product, Sales, SalesProducts
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError


class MyUserForm(ModelForm):
    class Meta:
        model=get_user_model()# returns the MyUser model class
        fields=["username", "password","first_name","last_name","phone","pan","adhar","passport"] #"__all__"


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = "__all__" #["name","discount"]
        exclude = [ "created_at"]

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ["hide","created_at"]

    # def clean(self):
    #     # this get called when you call form.is_valid method
    #     if not self.data.get("name").isalnum():
    #         raise ValidationError("Name expecting only numbers and alphabets")
    #     if self.data.get("discount")<0:
    #         raise ValidationError("Expecting discount>0")
    #     return super(CategoryForm, self).clean()

class SalesForm(ModelForm):
    class Meta:
        model = Sales
        fields = "__all__"
        exclude = ["products"]

class SalesProductsForm(ModelForm):
    class Meta:
        model = SalesProducts
        fields = "__all__"
        exclude = ["sales"]
product_form_set = formset_factory(SalesProductsForm, extra=1)

sales/product/views.py
from django.core.files.base import equals_lf
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from product.models import Category, Product, Sales, Customer
from django.contrib.auth.decorators import login_required
from product.forms import CategoryForm, product_form_set, SalesForm, ProductForm
from django.contrib import messages
from django.core.cache import cache
def view_product_create(request):
    if request.method=="POST":
        form = ProductForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(message="Product created successfully", request=request)
            return redirect("/products/")
        else:
            messages.error(message=form._errors, request=request)
    else:
        form = ProductForm()
    context = {"form": form}
    return render(request, "product_create.html", context)

def view_sales_create(request):
    context = {"customers": Customer.objects.all()}
    if request.method == "POST":
        sale_form = SalesForm(data=request.POST)
        total_product_forms = int(request.POST.get("form-TOTAL_FORMS"))
        initial_data = [{"cost":request.POST.get("form-%s-cost"%i),
                        "product":request.POST.get("form-%s-product"%i),
                        "quantity":request.POST.get("form-%s-quantity"%i),
                        } for i  in  range(total_product_forms)]
        product_forms = product_form_set(initial = initial_data)
        if "submit" in request.POST:
            if sale_form.is_valid():
                sale_form.instance.save()
                sale_id = sale_form.instance.id
                product_forms = product_form_set(request.POST)
                for product_form in  product_forms.forms:
                    if product_form.is_valid():
                        product_form.instance.sales_id=sale_id
                        product_form.instance.save()
                    else:
                        messages.error(messages=product_form._errors, request=request)
                messages.success(message="Sales Order submitted Successfully!",
                                    request=request)
                return redirect("/sales/")
            else:
                errors = []
                if sale_form._errors:
                    errors.append( sale_form._errors)
                # if product_forms._errors:
                #     errors.append(product_forms._errors)
                messages.error(message=errors, request=request)    
    else:
        sale_form = SalesForm()
        product_forms = product_form_set()
    context = {"sale_form":sale_form, "product_forms": product_forms}
    return render(request, "create_sales.html", context)

@login_required
def view_sales(request):
    contrext = {"data":Sales.objects.all()}
    return render(request, 'sales.html', contrext)
    

def view_products(request):
    context = {"data": Product.objects.all()}
    return render(request, "products.html", context)

def view_index(request):
    return render(request, "base.html")

# Create your views here.
def view_delete_customer(request, cust_id):
    cust_inst = Customer.objects.get(id=cust_id)
    if request.method == "POST":
        if "delete" in request.POST:
            cust_inst.delete()
            cache.delete("customers")
        return redirect("/customers/")
    context = {"data": cust_inst}
    return render(request, "confirm_customer.html", context)
    
    

def view_update_customer(request, cust_id):
    cust_inst = Customer.objects.get(id=cust_id)
    if request.method == "POST":
        cust_inst.name=request.POST.get("name")
        cust_inst.save()
        cache.delete("customers")
        return redirect("/customers/")
        #return view_categories(request)

    context = {"data": cust_inst}
    return render(request, "create_customer.html", context)
def view_create_customer(request):
    if request.method == "POST":
        data = request.POST
        cust_inst = Customer(name=data.get("name"))
        raise Exception("dsdfsdf")
        cust_inst.save()
        cust_inst.save(using="backup")
        cache.delete("customers")
        # context = {"cats": Customer.objects.all()}
        # return render(request, 'categories.html',context)
        return redirect("/customers/")
    return render(request, 'create_customer.html')

def view_customers(request):
    cache_data = cache.get("customers")
    if cache_data:
        data = cache_data
    else:
        data = Customer.objects.all()
        cache.set("customers",data)
    context = {"cats": data}

    return render(request, 'customers.html',context)




def view_hide_category(request, cat_id):
    cat_inst = Category.objects.get(id=cat_id)
    if request.method == "POST":
        if 'delete' in request.POST:
            cat_inst.hide=True
            cat_inst.save()
        return redirect("/categories/")
    context = {"data": cat_inst}# {"object": cat_inst}
    return render(request, "confirm.html", context)

sales/product/templates/add_product.html
{% extends 'base.html' %}
{% block content%}
    <h1>Add  Product</h1>
    Description: {{ sales_data.description}}
    Customer: {{ sales_data.customer}}
    <form method="post">
        {% csrf_token %}
        Products <select>
            {% for product in products%}
            <option value="{{ product.id }}">{{ product.name}}</option>
            {% endfor %}
        </select>
        Quantity<input type="text" name="quantity">
        cost <input type="text" name="cost">
        <input type="submit" value="Add">
    </form>
{% endblock %}

sales/product/templates/base.html
<html>
    <head>
      <title>SALES OPERATION</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <img src="/static/images/logo.png/" alt="LOGO" widht=50 height=50>
            </div>
            <div class="navbar-header">
              <a class="navbar-brand" href="#">SALES OPERATIONS</a>
            </div>
            <ul class="nav navbar-nav">
              {% if request.user.is_authenticated %}
              <li><a href="/categories/">Categories</a></li>
              <li><a href="/products/">Products</a></li>
               <li><a href="/sales/">Sales</a></li>
               <li><a href="/customers/">Customers</a></li>
               <li><a href="/signout/">Signout</a></li>
               {% else %}
               <li><a href="/signup/">SignUp</a></li>
               <li><a href="/signin/">SignIn</a></li>
               {% endif %}

            </ul>
          </div>
        </nav>
        <div class="container" style="margin-top:50px">
          <ul>
            {% for message in messages %}
              <li>{{message.level_tag }}::{{ message }}</li>
            {% endfor %}
          </ul>
            {% block content%}
                <h1>This site is for sales operations.</h1>
            {% endblock %}   
        </div>
    </body>
</html>

sales/product/templates/categories.html
{% extends 'base.html'%}
{% block content%}
    <h1>Categories</h1>
    <a href="/category/create/">CREATE CATEGORY</a>
    <table border="2">
        <tr><th>ID</th><th>NAME</th><th>OPERATIONS</th></tr>
        {% for cat in object_list %}
            <tr>
                <td>{{cat.id}}</td><td>{{ cat.name}}</td>
                <td><a href="/category/update/{{ cat.id }}/">UPDATE</a>||
                <a href="/category/delete/{{ cat.id }}/">DELETE</a>||
                <a href="/category/hide/{{ cat.id }}/">HIDE</a>
            </td>
            </tr>
        {% endfor %}
    </table>
    <p>Total: {{paginator.count}}
        showing:
        {% if page_obj.object_list.exists %}
             {{ page_obj.object_list.count}}</p>
        {% else %}
        0
        {% endif %}
    <p>{{ page_obj}}</p>
    {% if page_obj.has_previous %}
    <a href="/categories?page={{ page_obj.previous_page_number}}">PREVIOUS</a>
    {% endif %}
    {% if page_obj.has_next %}
    <a href="/categories?page={{ page_obj.next_page_number}}">NEXT</a>
    {% endif %}

{% endblock %}

sales/product/templates/confirm.html
{% extends 'base.html'%}
{% block content %}
        <h1>Delete Category</h1>
        <p>{{object.name}}</p>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="DELETE" name="delete">
        </form>
{% endblock %}

sales/product/templates/confirm_customer.html
{% extends 'base.html'%}
{% block content %}
        <h1>Delete Customer</h1>
        <p>{{data.name}}</p>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="DELETE" name="delete">
            <input type="submit" value="CANCEL" name="cancel">
        </form>
{% endblock %}

sales/product/templates/create_category.html
{% extends 'base.html' %}
{% block content%}
    <h1>create Category</h1>
    <form method="post">
        {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

sales/product/templates/create_customer.html
{% extends 'base.html' %}
{% block content%}
    <h1>create Customer</h1>
    <form method="post">
        {% csrf_token %}
        name: <input type="text" name="name" value="{{ data.name }}">
        <input type="submit" value="Submit">
    </form>
{% endblock %}

sales/product/templates/create_sales.html
{% extends 'base.html' %}
{% block content%}
    <h1>create Salesorder</h1>
    <form method="post">
        {% csrf_token %}
        {{ sale_form }}<br>
        {{ product_forms }}
        <input type="submit" value="Add product" name="add">
        <input type="submit" value="Submit" name="submit">
    </form>
{% endblock %}

sales/product/templates/customers.html
{% extends 'base.html'%}
{% block content%}
    <h1>Customers</h1>
    <a href="/customer/create/">CREATE customer</a>
    <table border="2">
        <tr><th>ID</th><th>NAME</th><th>OPERATIONS</th></tr>
        {% for cat in cats %}
            <tr>
                <td>{{cat.id}}</td><td>{{ cat.name}}</td>
                <td><a href="/customer/update/{{ cat.id }}/">UPDATE</a>||
                <a href="/customer/delete/{{ cat.id }}/">DELETE</a>||
                <a href="/customer/hide/{{ cat.id }}/">HIDE</a>
            </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

sales/product/templates/product_create.html
{% extends "base.html" %}
{% block content%}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token%}
        {{ form.as_p }}
        <input type="submit" value="Create product">
    </form>


{% endblock %}

sales/product/templates/products.html
{% extends 'base.html'%}
{% block content%}
    <h1>Products</h1>
    <a href="/product/create/">CREATE PRODUCT</a>
    <table border="2">
        <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>COST</th>
            <th>DELIVERY CHARGES</th>
            <th>category</th>
            <th>category discount</th>
            <th>IMAGE</th>
            <th>OPERATIONS</th>
        </tr>
        {% for product in data %}
            <tr>
                <td>{{product.id}}</td>
                <td>{{ product.name}}</td>
                <td>{{ product.cost}}</td>
                <td>{{ product.deliver_charges}}</td>
                <td>{{ product.category}}</td>
                <td>{{ product.category.discount}}</td>
                <td><img src="/media/{{product.image}}/" width=30 height=30></td>
                <td><a href="/product/update/{{ cat.id }}/">UPDATE</a>||
                <a href="/product/delete/{{ cat.id }}/">DELETE</a>||
                <a href="/product/hide/{{ cat.id }}/">HIDE</a>
            </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

sales/product/templates/sales.html
{% extends 'base.html'%}
{% block content%}
    <h1>Sales Orders</h1>
    <a href="/sales/create/">CREATE Sales Order</a>
    {% for sale_order in data %}
        <ul>
            <li>Customer: {{sale_order.customer }}</li>
            <li>Description: {{sale_order.description }}</li>
        </ul>
        <p></p>
        <table border="2">
            <tr>
                <th>Name</th>
                <th>category</th>
                <th>COST</th>
                <th>Quantity</th>
            </tr>
                {% for sale_product  in sale_order.salesproducts_set.all %}
                <tr>
                    <td>{{sale_product.product}}</td>
                    <td>{{sale_product.product.category}}</td>
                    <td>{{ sale_product.cost }}</td>
                    <td>{{ sale_product.quantity }}</td>
                </tr>
                {% endfor %}
        </table>
    {% endfor %}
    
{% endblock %}

sales/product/templates/signin.html
{% extends 'base.html'%}
{% block content%}
    <h1>LOGIN</h1>
    <p>{{ message }}</p>
    <form method="post">
        {% csrf_token %}
        username: <input type="text" name="username">
        password:<input type="password" name="password">
        <input type="submit" name="" value="SIGNIN">
        
    </form>
        
   
{% endblock %}

sales/product/templates/signup.html
{% extends 'base.html'%}
{% block content%}
    <h1>Signup</h1>
    <p>{{ message }}</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="" value="Signup">
        
    </form>
        
   
{% endblock %}